import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

function extractBase64(dataUri: string) {
  const parts = dataUri.split(',');
  const mimeMatch = parts[0].match(/:(.*?);/);
  return {
    mimeType: mimeMatch ? mimeMatch[1] : 'image/jpeg',
    data: parts[1]
  };
}

function getImageUrlFromResponse(response: any) {
  const parts = response.candidates?.[0]?.content?.parts || [];
  for (const part of parts) {
    if (part.inlineData) {
      const { mimeType, data } = part.inlineData;
      return `data:${mimeType || 'image/png'};base64,${data}`;
    }
  }
  throw new Error("No image generated by the AI.");
}

export async function enhanceImageAI(imageUrl: string) {
  const { mimeType, data } = extractBase64(imageUrl);
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: { data, mimeType }
        },
        {
          text: 'Turn this into a high quality professional studio portrait. Make it look beautiful and polished. Remove distracting background, fix lighting, use perfect studio lighting. Keep the face identical.'
        }
      ]
    }
  });

  return getImageUrlFromResponse(response);
}

export async function applyMagicAI(imageUrl: string, prompt: string) {
  const { mimeType, data } = extractBase64(imageUrl);
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: { data, mimeType }
        },
        {
          text: `Professional beauty studio edit. Apply the following styles to this portrait carefully, maintaining the subject's identity: ${prompt}. Photorealistic, high quality, studio lighting.`
        }
      ]
    }
  });
  
  return getImageUrlFromResponse(response);
}

export async function enhancePromptAI(prompt: string) {
  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: `You are an expert makeup and hair stylist assistant writing prompts for a generative AI image editor. 
    The user wants to apply the following style to their portrait: "${prompt}". 
    Enhance this prompt into a highly detailed, descriptive phrase focused on makeup, hair styling, lighting, and photorealism. 
    Keep it as a direct descriptive command describing the final portrait appearance. No conversational text, return ONLY the enhanced text prompt.`,
  });
  return response.text?.trim() || prompt;
}
